-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, CONCAT(CITY," ",STREET_ADDRESS1," ",STREET_ADDRESS2) AS '전체주소',
CONCAT(SUBSTR(TLNO,1,3),"-",SUBSTR(TLNO,4,4),"-",SUBSTR(TLNO,8,4)) AS 전화번호
FROM USED_GOODS_BOARD AS B INNER JOIN USED_GOODS_USER AS U
ON B.WRITER_ID = U.USER_ID
WHERE B.WRITER_ID IN 
    (
    SELECT WRITER_ID
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
    HAVING COUNT(WRITER_ID) >= 3
    )
GROUP BY USER_ID
ORDER BY USER_ID DESC