-- 코드를 입력하세요
# SELECT I.ANIMAL_ID AS ANIMAL_ID, O.NAME AS NAME
# FROM ANIMAL_INS AS I INNER JOIN ANIMAL_OUTS AS O
# ON I.ANIMAL_ID = O.ANIMAL_ID
# WHERE TIMESTAMPDIFF(DAY, I.DATETIME, O.DATETIME) < 0
# ORDER BY I.DATETIME

SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_INS I, ANIMAL_OUTS O
WHERE I.ANIMAL_ID=O.ANIMAL_ID AND I.DATETIME>O.DATETIME
ORDER BY I.DATETIME;